# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainMenu.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 775)
        

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.plotArea = QWidget(self.centralwidget)
        self.plotArea.setObjectName(u"plotArea")
        self.plotArea.setGeometry(QRect(10, 160, 600, 600))
        self.horizontalLayoutWidget_2 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 70, 901, 41))
        self.inputLayout = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.inputLayout.setSpacing(20)
        self.inputLayout.setObjectName(u"inputLayout")
        self.inputLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.inputLayout.setContentsMargins(10, 10, 10, 10)
        self.functionLabel = QLabel(self.horizontalLayoutWidget_2)
        self.functionLabel.setObjectName(u"functionLabel")
        font = QFont()
        font.setFamily(u"Times New Roman")
        font.setPointSize(14)
        self.functionLabel.setFont(font)
        self.inputLayout.addWidget(self.functionLabel)
        self.functionInput = QLineEdit(self.horizontalLayoutWidget_2)
        self.functionInput.setObjectName(u"functionInput")
        self.inputLayout.addWidget(self.functionInput)
        self.horizontalSpacer_3 = QSpacerItem(30, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.inputLayout.addItem(self.horizontalSpacer_3)
        self.lowerLimitLabel = QLabel(self.horizontalLayoutWidget_2)
        self.lowerLimitLabel.setObjectName(u"lowerLimitLabel")
        self.lowerLimitLabel.setFont(font)
        self.inputLayout.addWidget(self.lowerLimitLabel)
        self.lowerLimitSpin = QSpinBox(self.horizontalLayoutWidget_2)
        self.lowerLimitSpin.setObjectName(u"lowerLimitSpin")
        self.lowerLimitSpin.setMinimum(-999)
        self.lowerLimitSpin.setMaximum(999)
        self.inputLayout.addWidget(self.lowerLimitSpin)
        self.horizontalSpacer_4 = QSpacerItem(30, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.inputLayout.addItem(self.horizontalSpacer_4)
        self.upperLimitLabel = QLabel(self.horizontalLayoutWidget_2)
        self.upperLimitLabel.setObjectName(u"upperLimitLabel")
        self.upperLimitLabel.setFont(font)
        self.inputLayout.addWidget(self.upperLimitLabel)
        self.upperLimitSpin = QSpinBox(self.horizontalLayoutWidget_2)
        self.upperLimitSpin.setObjectName(u"upperLimitSpin")
        self.upperLimitSpin.setMinimum(-999)
        self.upperLimitSpin.setMaximum(999)
        self.inputLayout.addWidget(self.upperLimitSpin)
        self.horizontalSpacer_5 = QSpacerItem(30, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.inputLayout.addItem(self.horizontalSpacer_5)
        self.sampleNumberLable = QLabel(self.horizontalLayoutWidget_2)
        self.sampleNumberLable.setObjectName(u"sampleNumberLable")
        self.sampleNumberLable.setFont(font)
        self.inputLayout.addWidget(self.sampleNumberLable)
        self.sampleNumberSpin = QSpinBox(self.horizontalLayoutWidget_2)
        self.sampleNumberSpin.setObjectName(u"sampleNumberSpin")
        self.sampleNumberSpin.setMinimum(1)
        self.sampleNumberSpin.setMaximum(999)
        self.inputLayout.addWidget(self.sampleNumberSpin)
        self.horizontalLayoutWidget_3 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(0, 110, 901, 51))
        self.plotButtonLayout = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.plotButtonLayout.setSpacing(10)
        self.plotButtonLayout.setObjectName(u"plotButtonLayout")
        self.plotButtonLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.plotButtonLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.plotButtonLayout.addItem(self.horizontalSpacer_6)
        self.plotButton = QPushButton(self.horizontalLayoutWidget_3)
        self.plotButton.setObjectName(u"plotButton")
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setWeight(50)
        self.plotButton.setFont(font1)
        self.plotButtonLayout.addWidget(self.plotButton)
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.plotButtonLayout.addItem(self.horizontalSpacer_7)
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 901, 71))
        self.titleLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.titleLayout.setSpacing(10)
        self.titleLayout.setObjectName(u"titleLayout")
        self.titleLayout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.titleLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalSpacer_1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.titleLayout.addItem(self.horizontalSpacer_1)
        self.titleLabel = QLabel(self.horizontalLayoutWidget)
        self.titleLabel.setObjectName(u"titleLabel")
        font2 = QFont()
        font2.setFamily(u"Times New Roman")
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setItalic(True)
        font2.setWeight(75)
        self.titleLabel.setFont(font2)
        self.titleLayout.addWidget(self.titleLabel)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.titleLayout.addItem(self.horizontalSpacer_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Function Plotter", None))
        self.functionLabel.setText(QCoreApplication.translate("MainWindow", u"Function", None))
#if QT_CONFIG(tooltip)
        self.functionInput.setToolTip(QCoreApplication.translate("MainWindow", u"supported functions: \"sin, cos, sqrt, exp, ^\"", None))
#endif // QT_CONFIG(tooltip)
        self.lowerLimitLabel.setText(QCoreApplication.translate("MainWindow", u"Lower limit for X:", None))
#if QT_CONFIG(tooltip)
        self.lowerLimitSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Supports integers between -999 and 999", None))
#endif // QT_CONFIG(tooltip)
        self.upperLimitLabel.setText(QCoreApplication.translate("MainWindow", u"Upper limit for X:", None))
#if QT_CONFIG(tooltip)
        self.upperLimitSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Supports integers between -999 and 999", None))
#endif // QT_CONFIG(tooltip)
        self.sampleNumberLable.setText(QCoreApplication.translate("MainWindow", u"Number of samples", None))
#if QT_CONFIG(tooltip)
        self.sampleNumberSpin.setToolTip(QCoreApplication.translate("MainWindow", u"Needs to be =>100 to be smooth", None))
#endif // QT_CONFIG(tooltip)
        self.plotButton.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"Function Plotter", None))
    # retranslateUi

